### ISSUE TITLE
Error during installation on OSX: main.go:318: undefined: sort.SliceStable

### ISSUE THREAD

**Issue by wakaru44** [augustoroman/highlight#1]
Hi:

I just tried to install this in Mac OSX Sierra, and got this error.

```sh
..[$] <()> go get  -u github.com/augustoroman/highlight
# github.com/augustoroman/highlight
src/github.com/augustoroman/highlight/main.go:318: undefined: sort.SliceStable
```

My go version is 

```
..[$] <()> go version
go version go1.7.1 darwin/amd64
``` 

Any clue on how to fix it?

Congrats for the tool. I really like the syntax and how to specify the different highlights.

**Comment by augustoroman** [comment]
Ah -- sort.SliceStable is go 1.8 only.  I've pushed a fix so that it uses the old sort.Sort since there's no real reason that this utility should be go 1.8+ only, but you should still upgrade to the last version if possible.
